### ISSUE TITLE
Application boilerplate installation error

### ISSUE THREAD

**Issue by mbeghe** [interfaced/zombiebox#5] opened 2020-03-02 16:09 UTC
Hi everyone,

I was trying to run the biolerplate provided by the package and I can't seem to get it working.

Seems like some dependencies paths were changed on a new release. Below you can find the console error messages after trying to connect to http://localhost:1337/ :
![image](https://user-images.githubusercontent.com/26530999/75693900-72d29d80-5c86-11ea-9a60-44efcb40d8f5.png)

The steps to reproduce this error are detailed below:

1. Executed `npm init`

2. Executed `npm install zombiebox`

3. Executed `npm install zombiebox-platform-pc zombiebox-extension-cutejs`

4. Created `config.js` on root folder

5. Executed `npx zombiebox init zombiebox-spike` 

6. Executed `npx zombiebox run`

**Comment by l1bbcsg** [comment] 2020-03-03 07:30
Hello, thanks for trying ZombieBox.

I couldn't reproduce the issue with exactly those steps.

What was the contents of your `config.js` file that you created prior to running `zombiebox init`?
This file is not necessary at that step and in fact, `init` command generated a new one and overrode the one you created. But perhaps it changed the way CLI configured itself on the initialisation step and that affected the boilerplate.

You can also try the same steps minus step 4 to see if config file was the culprit.

Also note that recently ZombieBox CLI received a `--log-level` option that can help understand what's going on and pinpoint the issue. Try adding `--log-level debug` argument.

**Comment by mbeghe** [comment] 2020-03-03 12:55
@l1bbcsg actually I used the config.js from a previous `zombiebox init` since I was getting the below attached error, and I thought that was the main cause:
![image](https://user-images.githubusercontent.com/26530999/75777541-eb903300-5d34-11ea-9cff-691d01c05cb7.png)

Either way, I did tried what you stated and got the same result. I will go ahead and try running the CLI with loglevel tag.
![image](https://user-images.githubusercontent.com/26530999/75777632-0d89b580-5d35-11ea-87bd-6d718a360f37.png)

**Comment by mbeghe** [comment] 2020-03-03 13:28
@l1bbcsg I have tried running with` --log-level` tag and can't see anyhting abnormal.
![image](https://user-images.githubusercontent.com/26530999/75779437-5e4edd80-5d38-11ea-91f8-ea14edccf7fe.png)

And also the same result on `npx zombiebox run`:
![image](https://user-images.githubusercontent.com/26530999/75779494-7888bb80-5d38-11ea-911b-1a43d3ae3162.png)

 As I can see it is trying to reach a 'zb' dependency. While navigating `node_modules` I found out that the zombiebox package does have a subfolder under 'zb' name, and shares the structure from the GET request errors.
![image](https://user-images.githubusercontent.com/26530999/75780088-8b4fc000-5d39-11ea-81cf-8d78d094cdd2.png)

So my guess is that the path on those GET request are missing the zombiebox at the beginning

**Comment by l1bbcsg** [comment] 2020-03-03 13:33
Thanks, that rules out any issues with config.

We managed to reproduce this issue on Windows machine, so it appears to be some OS compatibility issue. ZombieBox should work on Windows, so that's definitely a bug somewhere in filesystem operations. 
I'll look into it, shouldn't be hard to pinpoint and fix.

**Comment by l1bbcsg** [comment] 2020-03-04 11:30
This was addressed in version `2.7.0`, the version was published to both github and npm and the issue should now be fixed.
No need to regenerate boilerplate or change existing applications, the changes are contained within ZombieBox engine.

**Comment by mbeghe** [comment] 2020-03-04 19:20
I did actually needed to regenerate the boilerplate! But now it works! Thanks a lot.

**Closed as completed** 2020-03-05 03:49 UTC
